#
# Executes commands at login post-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Execute code that does not affect the current session in the background.
{
  # Compile the completion dump to increase startup speed.
  zcompdump="${ZDOTDIR:-$HOME}/.zcompdump"
  if [[ -s "$zcompdump" && (! -s "${zcompdump}.zwc" || "$zcompdump" -nt "${zcompdump}.zwc") ]]; then
    zcompile "$zcompdump"
  fi
} &!

# Autostart X at login on tty1
[[ $EUID != 0 && -z $DISPLAY && $(tty) = /dev/tty1 ]] && exec xinit -- -nolisten tcp -br +bs -dpi 96 vt$XDG_VTNR
# systemd variant
#[[ $EUID != 0 && -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec xinit -- -nolisten tcp -br +bs -dpi 96 vt$XDG_VTNR

# Print a random, hopefully interesting, adage.
#if (( $+commands[fortune] )); then
#  fortune -a ~/.fortunes | cowsay -f small
#  print
#fi

if (( $+commands[fortune] )); then
  if [[ -t 0 || -t 1 ]]; then
    fortune -s
    print
  fi
fi
