#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# use comments in command line
setopt interactivecomments

# disable "file exists" warning with redirection
setopt clobber

# don't share history
unsetopt SHARE_HISTORY

# disable color diff output
unfunction diff

# editor and pager
export LIBVIRT_DEFAULT_URI="qemu:///system"
export MPD_HOST="/home/fedotov_sv/.mpd/socket"

# aliases
alias mailsql="/usr/bin/vim +8 ${HOME}/mail.sql"
alias coub_weekly="xdg-open http://coub.com/weekly/$(date +%Y)/$(date +%U)"
alias wgetcover='wget $1 -O cover.jpg'
alias ccat='pygmentize -g -O style=colorful,linenos=1'
alias ls='/bin/ls -N --group-directories-first --color=auto'
alias l='ls -1'
alias ll='ls -1l'
alias -g N='2>/dev/null'
alias vim='/usr/bin/nvim'

# bind backward search key "CTRL+?" (next occurence)
bindkey -M viins "^_" history-incremental-search-backward
unset GREP_OPTIONS

# bind key for external command editor
bindkey -M vicmd v edit-command-line

# completion for server-status.sh
compdef _hosts server-status.sh

# spaceship prompt options
SPACESHIP_PROMPT_ORDER=(
  time          # Time stampts section
  user          # Username section
  dir           # Current directory section
  host          # Hostname section
  #git           # Git section (git_branch + git_status)
  exec_time     # Execution time
  line_sep      # Line break
  vi_mode       # Vi-mode indicator
  jobs          # Background jobs indicator
  exit_code     # Exit code section
  char          # Prompt character
)

# show labels for ranger subshell and bitbake env (sorin theme)
#PS1="${PS1%$\{editor*}%F{1}\${BUILDDIR:+ BITBAKE}%f\${editor_info[keymap]} "
#
#if [ -n "$RANGER_LEVEL" ]; then
#    PS1="${PS1%$\{editor*} %F{3}RANGER%f\${editor_info[keymap]} "
#fi

