#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

if [[ -d "${HOME}/.gem/ruby/2.0.0/bin" ]]; then
  export PATH="${PATH}:${HOME}/.gem/ruby/2.0.0/bin"
fi
# Customize to your needs...

# use comments in command line
setopt interactivecomments

# disable "file exists" warning with redirection
setopt clobber

# don't share history
unsetopt SHARE_HISTORY

# disable color diff output
unfunction diff

# editor and pager
export LIBVIRT_DEFAULT_URI="qemu:///system"
export MPD_HOST="/home/fedotov_sv/.mpd/socket"

# aliases
alias mailsql="/usr/bin/vim +8 ${HOME}/mail.sql"
alias coub_weekly="xdg-open http://coub.com/weekly/$(date +%Y)/$(expr $(date +%U) - 1)"
alias wgetcover='wget $1 -O cover.jpg'
alias ccat='pygmentize -g -O style=colorful,linenos=1'
alias ls='/bin/ls -N --group-directories-first --color=auto'
alias l='ls -1'
alias ll='ls -1l'
alias vim='nvim'
alias nless='nvimpager -u NORC'
alias lessn='nvimpager -u NORC -'
alias -g N='2>/dev/null'

# bind backward search key "CTRL+?" (next occurence)
bindkey -M viins "^_" history-incremental-search-backward
unset GREP_OPTIONS

# completion for server-status.sh
compdef _hosts server-status.sh

# add local lua package paths
eval `luarocks path`
