#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# use comments in command line
setopt interactivecomments

# don't share history
unsetopt SHARE_HISTORY

# editor and pager
export EDITOR="vim"
export VISUAL=$EDITOR
export PAGER="vimpager"

# aliases
alias mailsql="vim +8 $HOME/mail.sql"
alias coub_weekly="xdg-open http://coub.com/weekly/$(date +%Y)/$(date +%U)"
alias fuck='eval $(thefuck $(fc -ln -1))'
alias less=${PAGER}
alias zless=${PAGER}
alias mc='ranger'

# temporary fix
unset GREP_OPTIONS
